apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
    hello: world
  name: test
spec:
  replicas: 10
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - image: nginx:1.29.4
        name: nginx
  strategy:
    type: Recreate
